### ISSUE TITLE
Missing critical information

### ISSUE THREAD

**Issue by jlehew** [awsdocs/amazon-cognito-developer-guide#10]
1.  Need to reference this repo for .net development:  https://github.com/awslabs/aws-alb-identity-aspnetcore
2.  The logic in the ConvertPemToSecurityKey method from that repo is critical to add or Cognito will not authenticate 
3.  It does not mention the RSA key rotates every week on Saturdays.  Must add logic to handle the rotation similar to what is done in the aws-alb-identity-aspnetcore repo, or every week on Saturday your entire API will go down responding with 401s until every container is restarted
4.  Must cache the rsa key from "https://public-keys.auth.elb.{0}.amazonaws.com/{1}"; otherwise the system will not scale past 25 requests per second as that is the default quota for the "public-keys" resource and will fail load testing
5.  Instructions on best methods to obtain tokens as this issue prevents aws from properly answer support tickets.  Of the 4 aws support resources I've worked with, none know about AWSELBAuthSessionCookie-0 and -1 cookies and how these are converted by the ALB to real tokens.  Writing tokens to the log is against security policy at the fortune 50 company I work at
6. Nice if there was an example of how to implement PKCE in .net core for Cognito
7. Need better instructions on how to set the callback urls in Cognito, we spent too much time troubleshooting these and learned there has to be a space between each comma separated url 
8. The Visio diagram I created to explain how Cognito works to other architects and security engineers has 24 steps to log in, hit the api to get basic user info, and open a welcome page.  This understanding is time consuming to achieve and would help if more flow diagrams were created
9. Need to describe the popup that displays if more than one authentication method is available for example ADFS and local Cognito Userpool users.  I understand why this would display if more than one method is configured in Cognito but with only one method some of our users are seeing this selection page and they submit help tickets

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
