### ISSUE TITLE
Exchanging a refresh token for tokens does not provide a refresh token in the response

### ISSUE THREAD

**Issue by SampathDilhan** [awsdocs/amazon-cognito-developer-guide#13]
According to Cognito [TOKEN Endpoint documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html), when we exchange a refresh token for new tokens, it should return a `refresh_token` along with `id_token` and `access_token`. 

It has mentioned under the section _Exchanging a Refresh Token for Tokens_:
>Sample Response
HTTP/1.1 200 OK
                                 Content-Type: application/json
 {
   "access_token":"eyJz9sdfsdfsdfsd", 
   "refresh_token":"dn43ud8uj32nk2je",
   "id_token":"dmcxd329ujdmkemkd349r",
  "token_type":"Bearer", 
  "expires_in":3600
  }

However, when I tested this  `refresh_token` was not there in the response. All the other fields were there. 
Please note that I was using Authorization Code Flow.

**Comment by AMZ-brandon** [comment]
Hi, thanks for noticing that! The sample request is now updated to note that a refresh token request doesn't return a new refresh token.
