### ISSUE TITLE
Logout endpoint doesn't return state parameter

### ISSUE THREAD

**Issue by heidenator** [awsdocs/amazon-cognito-developer-guide#15]
when calling the logout endpoint coginto logs the user out however when it redirect back to the logout_uri it doesn't add the state variable when redirecting back.  This cause the sign out to hang to on logout. for any application using open id connect. OIDC expects the state query string parameter to be there once the redirect happens to validate the response.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
