### ISSUE TITLE
MigrateUser: Unknown References

### ISSUE THREAD

**Issue by haelmj** [awsdocs/amazon-cognito-developer-guide#33]
https://github.com/awsdocs/amazon-cognito-developer-guide/blob/d3a11e2a02b8019e51f8f1ee6530cd66bde23cdf/doc_source/user-pool-lambda-migrate-user.md?plain=1#L109

https://github.com/awsdocs/amazon-cognito-developer-guide/blob/d3a11e2a02b8019e51f8f1ee6530cd66bde23cdf/doc_source/user-pool-lambda-migrate-user.md?plain=1#L127

This code snippet doesn't clarify the references to these functions made. The information being left out here isn't one that can be readily sourced by a developer, let alone a junior one. As such, the code snippets need to be more explicit about what functions are being called or provide references to where related information can be found.

**Comment by AMZ-brandon** [comment]
Hi @haelmj, I'm the current Cognito writer. I agree that those examples leave the functions undeclared. This is because there are many ways you can source your credentials for a migrate user trigger. We're working on improving our code examples, but I think a short-term stopgap would be to insert a comment into the code example saying that the functions are yours to define, but lookupUser should query your existing directory.

**Comment by haelmj** [comment]
@AMZ-brandon Thanks for the response, I believe the comment will be most helpful. Where does `lookupUser` come from though? The lambda code editor just flags it marked as undefined.

![image](https://user-images.githubusercontent.com/67227582/170390498-5af2efe5-b5a5-4fbb-8599-331cc0c21784.png)

**Comment by AMZ-brandon** [comment]
It's expected that you define it elsewhere in your function. The sample isn't a complete function. Say you've got AD. 
Your authenticateUser function might do an [ldap-authentication](https://www.npmjs.com/package/ldap-authentication) call, verifying that the username and password that Cognito passed to the function can sign in to your domain. It would also have to assign a value to user.emailAddress, which the function passes to the "email" attribute in the response.
Your lookupUser function gets called if the input event is a forgot-password request. In that case, it only has access to the user name, not the password, so it can't look up the user. Instead, it does an LDAP query for the user's email address and returns it to Cognito, which uses that email address to send a password-reset email. When the user responds to that email, their password is set and they're ready to sign in.
My update to the page would be to add to the code example a declaration of those functions, but they're empty. They just have comments in them describing what the functions should do.
If you have an idea of what you'd like to see, I'd welcome a pull request, and I'll do my best to incorporate your suggestions into the [authoritative docs](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-migrate-user.html#aws-lambda-triggers-user-migration-example-1), which get replicated to GitHub.
Something like:
```
function authenticateUser (username, password) {
// This function should try to sign in your user to your existing directory
}
function lookupUser (username) {
// This function should query your existing directory for the user's email address
}
```

Cheers, and thanks for the feedback!

**Comment by haelmj** [comment]
@AMZ-brandon Apologies for the delay, I hadn't gotten around to make this pull request. Will put it through soon.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
