### ISSUE TITLE
AWS documentation broken links to github

### ISSUE THREAD

**Issue by severel** [awsdocs/amazon-cognito-developer-guide#34]
These pages

https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-info-in-cloudtrail.html

https://docs.aws.amazon.com/cognito/latest/developerguide/understanding-amazon-cognito-entries.html

Have broken links when you click "Edit this page on GitHub"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
