### ISSUE TITLE
Utilising Async Examples

### ISSUE THREAD

**Issue by haelmj** [awsdocs/amazon-cognito-developer-guide#36]
https://github.com/awsdocs/amazon-cognito-developer-guide/blob/d3a11e2a02b8019e51f8f1ee6530cd66bde23cdf/doc_source/user-pool-lambda-migrate-user.md?plain=1#L102

The functionality of the handler in this migration seems to require utilizing asynchronous functions. The [nodejs handler docs](https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/nodejs-handler.md) clarifies that callbacks shouldn't be used with async handlers.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/67227582/184937712-2a829d82-c393-4075-93b7-7a8f03936dd0.png">

Can the docs be updated to reflect this?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
