### ISSUE TITLE
MigrateUser: Callback Error Message Not Reflecting

### ISSUE THREAD

**Issue by haelmj** [awsdocs/amazon-cognito-developer-guide#37]
https://github.com/awsdocs/amazon-cognito-developer-guide/blob/d3a11e2a02b8019e51f8f1ee6530cd66bde23cdf/doc_source/user-pool-lambda-migrate-user.md?plain=1#L121

https://github.com/awsdocs/amazon-cognito-developer-guide/blob/d3a11e2a02b8019e51f8f1ee6530cd66bde23cdf/doc_source/user-pool-lambda-migrate-user.md?plain=1#L144

<img width="265" alt="image" src="https://user-images.githubusercontent.com/67227582/184938522-ac05ffd7-f922-4ace-b42f-3dcb2519bed2.png">

I noticed that the error messages passed to the callbacks aren't being reflected on the web page instead a generic 'Incorrect username or password' error is shown. This isn't very helpful considering that not all errors are relative to the username or password so it is useful to have custom error messages. Is there a way to achieve this?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
