### ISSUE TITLE
Triggers: Adding In Python Snippets

### ISSUE THREAD

**Issue by haelmj** [awsdocs/amazon-cognito-developer-guide#39]
I noticed that for the following lambda triggers, there isn't any python code snippets available and only examples utilising Node.js

- [ ] Post Confirmation 
- [ ] Auth Challenge
- [ ] Custom email sender
- [ ] Custom message
- [ ] Custom SMS sender
- [ ] Pre-token Generation
- [ ] Verify Auth Challenge
- [x] Migrate User

I thought it would be good to add python snippets to improve the documentation as well as maintain uniformity across the documentation.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
