### ISSUE TITLE
Broken links - Android and iOS Samples for Cognito is deprecated

### ISSUE THREAD

**Issue by lawmicha** [awsdocs/amazon-cognito-developer-guide#4]
The links located here: https://github.com/awsdocs/amazon-cognito-developer-guide/blob/main/doc_source/user-pool-settings-viewing-advanced-security-app.md

point to the Android and iOS samples. They were recently removed from the main branch and deprecated.

For example, on iOS, the previous commit containing the sample would be here: https://github.com/awslabs/aws-sdk-ios-samples/tree/3581aabff0213a61652989545453c5d78ec9cd21/CognitoAuth-Sample

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
