### ISSUE TITLE
Correction in documentation.

### ISSUE THREAD

**Issue by Aryancsz** [awsdocs/amazon-cognito-developer-guide#44]
![image](https://user-images.githubusercontent.com/73257543/209428550-23211936-d4b5-4443-b196-2241d4fd9184.png)

`KMSKeyID= key-id`
is not accepting the id in CLI
it requires kms ARN,  error shown is a regex error which accepts only ARN.

corrections 
`KMSKeyID= key-id` ==> `KMSKeyID= KMS-Key-arn`

Ref : https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-email-sender.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
