### ISSUE TITLE
Missing Information about alternatives

### ISSUE THREAD

**Issue by lpiedade** [awsdocs/amazon-cognito-developer-guide#47]
This page [application-client-based-multi-tenancy](https://github.com/awsdocs/amazon-cognito-developer-guide/blob/main/doc_source/application-client-based-multi-tenancy.md) mention that session cookie is valid for one hour and it can't be changed.

That's true, but it's possible to use **refresh token** mechanism to get new token without user interaction. 
Please add this info and give the direction to this [page](https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-refresh-token.html)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
