### ISSUE TITLE
federation: mismatched lambda trigger label on subsequent sign ins

### ISSUE THREAD

**Issue by exaucae** [awsdocs/amazon-cognito-developer-guide#50]
It looked to me that the `Federated user trigger sources`section of [lambda triggers doc](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-identity-pools-working-with-aws-lambda-trigger-sources) has a mismatch in the given entry: <html>
<body>

Lambda trigger | Trigger source
-- | --
Post confirmation | PreAuthentication_Authentication
-- | --

</body>
</html>

<html>
<body>

**I postulate the lambda trigger name should be `Pre authentication`.** It may be the other way around ( trigger source being Post_Confirmation). But that doesn't follow the logic governing the rest of the doc.

![typo-aws](https://github.com/awsdocs/amazon-cognito-developer-guide/assets/64139733/02b31432-e07c-4f23-b44a-1d62f6cf0ad4)

This one is either a small fix, or a non event.

If it's a fix, I'd be glad to have it. Oddly enough, [the source code of that page](https://github.com/awsdocs/amazon-cognito-developer-guide/blob/3c95b010c7fcf5aa7688cea2e8cb85bcb493d6ea/doc_source/cognito-user-identity-pools-working-with-aws-lambda-triggers.md?plain=1#L217-L220) doesn't have the problematic table, let alone the entry. I may just be unaware of its exact location. In which case I request it.

If there's nothing to see here, I'll close this issue.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
